enum UserMbtiType {
  LAIDBACK_EXPROLER = "AHN",
  EXTROVERTED_DRIFTER = "AIO",
  LEADING_GUIDE = "STP",
  EFFICIENT_TRAVELER = "SHF",
  EMOTIONAL_VACATIONER = "HFN",
  IMPROVISED_FOLLOWERS = "HTN",
}

export default UserMbtiType;
